# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

skin: "/assets/css/skins/default.css"
locale: en-US
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
title: Becky Dale Daly Design
email: beckydaledesign@gmail.com
description: Design | Project Managment | Construction
keywords: Interior Exterior Design Project Managment Construction
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: "project"
      image_path: "/assets/images/projects"
      # share: true
      # image_gallery: true

  # images defaults
  - scope:
      path: "assets/images/projects"
    values:
      image: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - brentwood.md
      - westchester.md
      - oasis.md
      - white-marble.md
      - coastal.md
      - loft-apartment.md
      - golf-resort.md
      - stage-prep.md
      - manhattan-beach.md

# Site Author
author:
  name: Becky Dale Daly
  avatar: "/assets/images/bio-photo-mini.png"
  email: "beckydaledesign@gmail.com"
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:beckydaledesign@gmail.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/beckydaledaly/"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/beckydaledaly/"
    - label: "Website"
      icon: "/assets/images/favicon.ico"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
