# Welcome to Jekyll!

skin: "/assets/css/skins/default.css"
locale: en-US
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
title: Becky Dale Daly Design
email: beckydaledesign@gmail.com
description: Design | Project Managment | Construction
keywords: Interior Exterior Design Project Managment Construction
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: "gallery"
      image_path: "/assets/images/projects"
      # share: true
      # image_gallery: true

  # images defaults
  - scope:
      path: "assets/images/projects"
    values:
      image: true
      
include:
  - assets
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - brentwood.md
      - westchester.md
      - oasis.md
      - white-marble.md
      - coastal.md
      - loft-apartment.md
      - golf-resort.md
      - stage-prep.md
      - manhattan-beach.md

# Site Author
author:
  name: Becky Dale Daly
  avatar: "/assets/images/bio-photo-mini.png"
  email: "beckydaledesign@gmail.com"
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:beckydaledesign@gmail.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/beckydaledaly/"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/beckydaledaly/"
    - label: "Website"
      icon: "/assets/images/favicon.ico"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
